# Generated by Django 4.0.4 on 2022-05-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_posts_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='id',
            field=models.IntegerField(default=2285668103996445164, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
