# Generated by Django 4.0.4 on 2022-05-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_posts_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='id',
            field=models.BigIntegerField(default=15805705035583787500, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
