# Generated by Django 4.0.4 on 2022-05-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_posts_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='id',
            field=models.BigAutoField(default=7098143963794903532, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
