# Generated by Django 4.0.4 on 2022-05-18 11:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_rename_id_posts_article_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='article_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
