# Generated by Django 4.0.4 on 2022-05-18 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_posts_article_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='article_id',
            new_name='id',
        ),
    ]
