# Generated by Django 4.0.4 on 2022-05-18 11:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_rename_article_id_posts_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='id',
            field=models.IntegerField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
